server:
  port: ${config.registryCenterB.port}
spring:
  application:
     name: registryCenter

eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${config.registryCenterA.port}/eureka/,http://${eureka.instance.hostname}:${config.registryCenterB.port}/eureka/