config:
  defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: ${config.defaultZone}
server:
  port: 6001

spring:
  application:
    name: service-consumer